name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: SonarCloud Scan
      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=ishandilmith
            -Dsonar.projectKey=IshanDilmith_order-microservice

      # Step 3: Login to ACR using admin credentials
      - name: Login to ACR
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      # Step 4: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/order-microservice:${{ github.run_number }} .

      # Step 5: Push Docker image to ACR
      - name: Push to ACR
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/order-microservice:${{ github.run_number }}

      # Step 6: Deploy to Azure Container Apps
      - name: Deploy to Azure Container Apps
        run: |
          az containerapp update \
            --name order-microservice-app \
            --resource-group CTSE \
            --image ${{ secrets.ACR_LOGIN_SERVER }}/order-microservice:${{ github.run_number }}